# Generated by Django 3.2.6 on 2021-08-31 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custmanageapp', '0004_auto_20210831_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tags',
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(to='custmanageapp.Tag'),
        ),
    ]
